---
- hosts: webservers
  become: true
  tasks:
  - name: Stop Tomcat
    service: name=tomcat state=stopped
  - name: Check that war file exist
    stat:
      path: /usr/share/tomcat/webapps/vprofile-v1.war
    register: stat_result

  - name: Delete the war file, if it exist already
    file:
      path: /usr/share/tomcat/webapps/vprofile-v1.war
      state: absent
    when: stat_result.stat.exists == True
  - name: Check that GAMEOFLIFE dir exist
    stat:
      path: /usr/share/tomcat/webapps/nodeapp-cicd
    register: stat_result
  - name: Delete the GAMEOFLIFE dir, if it exist already
    file:
      path: /usr/share/tomcat/webapps/nodeapp-cicd
      state: absent
    when: stat_result.stat.exists == True
  - name: Deploy War File
    get_url:
       url: http://35.154.72.227:8081/nexus/service/local/artifact/maven/redirect?r=releases&g=com.visualpathit&a=vprofile&p=war&v=LATEST
       dest: /usr/share/tomcat/webapps/vprofile-v1.war
  - name: Start Tomcat
    service: name=tomcat state=started
