---
- hosts: webservers
  become: true
  tasks:
  - name: stop tomcat
    shell: nohup /apache-tomcat-8.5.51/bin/shutdown.sh
  - name: cleaning the existing war file
    file: path=/apache-tomcat-8.5.51/webapps/vprofile-v1.war state=absent
  - name: deploy the war
    get_url: url=http://13.234.34.22:8081/nexus/service/local/artifact/maven/redirect?r=releases&g=com.visualpathit&a=vprofile&p=war&v=LATEST dest=/apache-tomcat-8.5.51/webapps/vprofile-v1.war
  - name: start tomcat
    shell: nohup /apache-tomcat-8.5.51/bin/startup.sh
